"""add saved_videos to chat_sessions

Revision ID: 65d9daa8deaa
Revises: acd4cd9b6d56
Create Date: 2025-07-03 10:20:52.107991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d9daa8deaa'
down_revision: Union[str, Sequence[str], None] = 'acd4cd9b6d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('saved_videos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'saved_videos')
    # ### end Alembic commands ###
