"""added embedding to check prompts relations

Revision ID: e894394706c2
Revises: 65d9daa8deaa
Create Date: 2025-07-03 11:07:18.811491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e894394706c2'
down_revision: Union[str, Sequence[str], None] = '65d9daa8deaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_prompt_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'last_prompt_embedding')
    # ### end Alembic commands ###
